# Generated by Django 5.0.2 on 2024-02-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('technology', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('image_main', models.ImageField(upload_to='images/')),
                ('image_1', models.ImageField(blank=True, upload_to='images/')),
                ('image_2', models.ImageField(blank=True, upload_to='images/')),
                ('image_3', models.ImageField(blank=True, upload_to='images/')),
                ('image_4', models.ImageField(blank=True, upload_to='images/')),
                ('image_5', models.ImageField(blank=True, upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
